# For more info on HTTP files go to https://aka.ms/vs/httpfile

# Docker
POST http://localhost:33640/api/securitynl/msi
Content-Type: multipart/form-data

Resource=https://vault.azure.net


###

POST http://localhost:7223/api/securitynl/msi
Content-Type: multipart/form-data

Resource=https://vault.azure.net